### PR TITLE
Add JavaScript linting and GitHub workflow for testing

### PR DESCRIPTION
**Pull request by KristjanESPERANTO**
To continue tackling issue #297, I'm adding **JavaScript linting** and a **GitHub workflow** that runs the linting and spelling tests on every push and pull request.

I've deliberately set soft linting rules. If I set harder rules, the resulting code changes would certainly cause ugly merge conflicts of old pull requests.
We can make the linter rules harder after we have dealt with the old pull requests.

### CODE REVIEW

**Comment by KristjanESPERANTO** [comment]
We could easily fix them, but then we would have problems with merging some older pull requests. My plan was to deal with the warnings later. But we can pursue a different strategy and take care of this linter issues now. I would also agree to that :slightly_smiling_face:

**Comment by ezeholz** [comment]
I see!

I propose to merge this PR and the olders that seems worth to have. And making the next step to fix the linter.
We shouldn't be procrastinating those fixes too much, as that may generate a snowball effect.

Maybe after the fix, we can plan a release, and come back with testings after it.

How does that sound to you?

**Comment by KristjanESPERANTO** [comment]
Sounds good! :smiley:

**Comment by KristjanESPERANTO** [comment]
@ezeholz I suggest to merge this PR and #305 and then do a minor release :slightly_smiling_face:

**Pull request merged**
