### PR TITLE
Confirmation dialog box for the shutdown and restart functions

### PR DESCRIPTION
**Pull request by davystrong**
Because of how frequently I accidentally shut down my mirror while using the remote control on my phone, I decided to implement a confirmation box for both the shutdown and restart function based on the confirmation dialog for the "Edit config.js" function. It's basically a copy of that but with custom text and icons. Unfortunately, as I only know english and portuguese, I had to use google translate for other languages.

### CODE REVIEW

**Comment by Jopyth** [comment]
I like the change, and can add a better german translation. I will tag the original contributors for these translations, maybe they can check these translations. This should be based on the develop branch though (which also includes a new dutch translation).

**Comment by Jopyth** [comment]
@slametps @sniparsdogg Could you briefly check these translations?

@QNimbus Can we use "Het systeem wordt uitgeschakeld." and "Het systeem wordt opnieuw gestart." and what would be the right word for "Cancel" in a confirmation dialog?

I hope you can help and thank you very much in advance.

**Comment by Snille** [comment]
Hi! No problem.
In sv.js change "Annullera" to "Avbryt".
Other then that it's all good. :)

**Comment by sniparsdogg** [comment]
I can confirm the portuguese translations are correct :)

**Comment by QNimbus** [comment]
@Jopyth The Dutch translations seem correct!

**Pull request merged**
