### PR TITLE
[Proposed v2.0.0-dev] Extensible REST API, Dynamic Menus, and Socket Communications, plus other updates

### PR DESCRIPTION
**Pull request by shbatm**
I hope you don't mind the intrusion, but I really like your module and I've been working on an updated version to truly make it "THE" remote for MagicMirror.  If you don't want to incorporate my changes to the original channel, that's fine... I just wanted to share.

### Description

I created an updated version with an extensible REST API for controlling everything about your mirror, as well as an upgrade of the `/remote.html` tool to use the module's node_helper socket connection for communication back and forth--instead of get/post calls.

#### Example REST Calls:
**Turn on the monitor**
```shell
GET /api/monitor/on  (curl -X GET 'http://magicmirror:8080/api/monitor/on')
```

**Hide All Modules**
```shell
GET /api/modules/all/hide (curl -X GET 'http://magicmirror:8080/api/modules/all/hide')
```
Here's the link to the [API README](https://github.com/shbatm/MMM-Remote-Control/tree/develop/API) and [API Documentation](https://documenter.getpostman.com/view/6167403/Rzfni66c).  The API also includes the ability to automatically interpret other modules' anticipated notifications to create a "guessed" API to control it (created from [MMM-API](https://github.com/juzim/MMM-API)).  Modules' can also send a notification to this module to explicitly declare their own API actions. 

### Inspiration

I've now written several modules and end of constantly including similar functions into my code (things like monitor control, module switching, etc.) for the different modules and I wanted to start migrating to a "One Remote to Rule Them All"-style module.  @Jopyth's module is an awesome base with a lot of the functions needed already built in, but I also wanted to have a better RESTful interface (inspired by [@juzim](https://github.com/juzim)'s [MMM-API](https://github.com/juzim/MMM-API) module incorporated in natively so I could control the mirror from my home automation devices.  Eventually, I'll scrub my other modules like [MMM-OnScreenMenu](https://github.com/shbatm/MMM-OnScreenMenu) and [MMM-KeyBindings](https://github.com/shbatm/MMM-KeyBindings) to just call the functions from this module and keep them focused on their own key features.

#### Added:

- REST API interface for controlling all aspects of the MagicMirror from HTTP RESTful-style GET and POST calls, based on principles from [MMM-Api](https://github.com/juzim/MMM-Api)
    + Full API Documentation at [API/README.md](API/README.md)
    + Extensible Actions -- Interprets other modules' notifications to "guess" an API, but also allows a module to explicitly provide API actions to use.
- Live daily updates of `modules.json` from the MagicMirror wiki, based on @eouia's [MMM-Remote-Control-Repository](https://github.com/eouia/MMM-Remote-Control-Repository).  
- Incorporated some features found in [MMM-OnScreenMenu](https://github.com/shbatm/MMM-OnScreenMenu) that were not originally in this module.
    + Monitor (Connected Screen) On-Off Status and Toggle
    + If using Electron: Open Dev Tools, Minimize, Toggle Fullscreen
- Configuration Option to send custom shell commands to use. Currently, only custom monitor on/off/status commands are supported. Addresses #99 

#### Changed:

- Updates to `remote.html` and the `node_helper.js` to use direct SocketIO communication back and forth instead of separate HTTP calls.
    + Future framework for following PM2 logs and more live update options.
- General clean-up and standardization of status reporting for GET and POST calls, to original URLs and to new API URLs.
- Updated to ES2015 (ES Version 6) function calls in most locations.
- Added USER_PRESENCE controls from [AgP42](https://github.com/AgP42), PR #84
- Added translations from [BKeyport](https://github.com/Bkeyport), PR #103
- Added SHOW/HIDE/TOGGLE ALL modules option per request from [Rene1709](https://github.com/Rene1709), #101

### CODE REVIEW

**Comment by Jopyth** [comment]
This looks awesome.

**Comment by Jopyth** [comment]
Hopefully I will find a few hours until the end of this year to merge this.

**Comment by shbatm** [comment]
Thanks! I had a good base to start from, though...
I'm still adding some features from my list, so no hurry to merge, but I could certainly use some extra eyes for testing.

The last big thing I wanted to add is custom remote menu items, dynamically loaded from the "guessed" API functions. This will allow for tap and send notifications, and, as long as the other module developer follows the standard notification conventions, you don't have to specifically "add" support for other modules to control them. Item's can also be loaded from a user's config or json file.

**Comment by shbatm** [comment]
@Jopyth OK -- I'm done adding major features for now, if you have any questions when you get around to looking at the changes, please let me know.

The last feature set I added was for Dynamic Menus -- 
1. Custom Menu - Allows a user to specify a custom menu in a JSON file (sample provided) 
2. Module Controls - Waits for the API "discovery"/"guessing" of other modules' `notificationReceived` functions and then creates a dynamic menu to call each modules' function.

Both of these are in the spirit of expanding control to other modules, but do so in a way that this module doesn't have to be manually updated to support everyone else's modules individually.

I have a few more ideas that I'll implement and push at a later date (such as live module position changes without a restart, and the ability to enter text for a Module Controls menu item (most likely something like a long-press to open the alert form).

**Pull request merged**
