### PR TITLE
Improved MagicMirror restart button

### PR DESCRIPTION
**Pull request by ronanversendaal**
- Allows multiple commands for the incoming pm2 query action.
- Adds restart method with restart action.

### CODE REVIEW

**Comment by bolish** [comment]
Hi @ronanversendaal ,

I've just tried your fix proposal (RESTART not working) and get the below errors (and restart is not working in the end...)
Did you experienced that on your side and do you know how I could fix that?

`Error: Cannot find module 'pm2'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Class.controlPm2 (/home/pi/MagicMirror/modules/MMM-Remote-Control/node_helper.js:867:23)
    at Class.executeQuery (/home/pi/MagicMirror/modules/MMM-Remote-Control/node_helper.js:654:22)
    at /home/pi/MagicMirror/modules/MMM-Remote-Control/node_helper.js:152:39
    at Layer.handle [as handle_request] (/home/pi/MagicMirror/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/pi/MagicMirror/node_modules/express/lib/router/route.js:137:13)`

**Comment by ronanversendaal** [comment]
That means you don't have pm2 installed or you have to link it with `npm link pm2`. There's a link to an issue in the comments where I had to do the same.

**Comment by bolish** [comment]
OK thx, I will give it a try

**Comment by bolish** [comment]
Worked perfect. Thx

**Comment by Gandohr** [comment]
Still have this error.
Pm2 restart mm trough SSH works. So pm2 is installeert.
Did the npm link pm2 and got
/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/pm2 -> /usr/lib/node_modules/pm2
As a result. Error stil remaims.
Sugestions?

**Comment by ezeholz** [comment]
I have the following error, does it have sense? @ronanversendaal 
```
[02:28:30.197] [LOG]    PM2 process: restart mm
[02:28:30.549] [LOG]    Whoops! There was an uncaught exception...
[02:28:30.551] [ERROR]  ReferenceError: action is not defined
    at pm2.restart (/home/username/Descargas/MagicMirror/modules/MMM-Remote-Control/node_helper.js:882:73)
    at /usr/lib/node_modules/pm2/lib/API.js:1538:25
    at /usr/lib/node_modules/pm2/lib/Client.js:733:12
    at /usr/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/client.js:45:10
    at Parser.<anonymous> (/usr/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/req.js:67:8)
    at Parser.emit (events.js:182:13)
    at Parser._write (/usr/lib/node_modules/pm2/node_modules/amp/lib/stream.js:91:16)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at Parser.Writable.write (_stream_writable.js:294:11)
```

**Comment by ronanversendaal** [comment]
@ezeholz Could be that it's the same issue. It's been a while so i'm not aware of the status of this issue. You can look https://github.com/Jopyth/MMM-Remote-Control/issues/118 here to see if it's the same problem and a possible fix

**Comment by ezeholz** [comment]
So I made my way to bypass that error, simply changing:
`this.sendResponse(res, undefined, { action: action, processName: processName});`
for:
`this.sendResponse(res, undefined, { action: actionName, processName: processName});`

But there is another problem. Of course I use `npm link pm2` in the Remote Control folder.
`Error: process or namespace not found`

I don't know what to do next, don't really know pm2.

**Pull request merged**
